name: Build 5S TES Containers

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - ".github/workflows/5S-TES-containers.yaml"
      - "Agent/agent-web/**"
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - "main"
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - ".github/workflows/5S-TES-containers.yaml"
      - "Agent/agent-web/**"

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  containers:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v2.1.2-repo
    with:
      job-name: containers
      release-tag-format: 'v${version}-5S-TES-containers'      

  agent-web-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v2.1.0-bulk-containers
    with:
      job-name: ui-container
      comment-pr: "true"
      comment-release: "true"
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO_AGENT_WEB }}
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: Agent/agent-web/Dockerfile
      build-context: Agent/agent-web
      platforms: "linux/amd64,linux/arm64"
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}


